### ISSUE TITLE
Upgrade Phoenix to v1.6

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#72]
Resources:
- blog post: https://phoenixframework.org/blog/phoenix-1.6-released
- changelog: https://github.com/phoenixframework/phoenix/blob/eb1deb6c05691dbebeacc35c2acd671b94ddb59f/CHANGELOG.md#changelog-for-v16
- upgrade instructions: https://gist.github.com/chrismccord/2ab350f154235ad4a4d0f4de6decba7b#phoenix-15x-to-16-upgrade-instructions

Interesting changes for us:
- use of esbuild to replace node/npm/webpack

---

My upgrade notes:
- requires Elixir v1.12  (previously v1.11 was fine)
- [don't migrate to esbuild for now](https://github.com/dsgelab/risteys/issues/72#issuecomment-930180476)
- [don't use `@view_module` anymore](https://github.com/dsgelab/risteys/issues/72#issuecomment-930183685)

**Comment by vincent-octo** [comment]
Just following [the migration to esbuild](https://gist.github.com/chrismccord/2ab350f154235ad4a4d0f4de6decba7b#migrate-to-esbuild-for-js-and-css-bundling-optional) lead to errors (below).
I don't understand enough about the JS ecosystem to know how to properly solve them. Especially the Vue error seems more difficult to solve, if even solvable.

**Skipping migration to esbuild**, will stick with the current setup.

```
mix assets.deploy
 > js/app.js:1:16: error: Could not resolve "vue" (mark it as external to exclude it from the bundle)
    1 │ import Vue from 'vue';
      ╵                 ~~~~~

 > js/app.js:22:22: error: Could not resolve "lodash-es" (mark it as external to exclude it from the bundle)
    22 │ import {forEach} from "lodash-es";
       ╵                       ~~~~~~~~~~~

 > js/app.js:34:26: error: No loader is configured for ".vue" files: js/HelpMortality.vue
    34 │ import HelpMortality from './HelpMortality.vue';
       ╵                           ~~~~~~~~~~~~~~~~~~~~~

 > js/app.js:27:22: error: No loader is configured for ".vue" files: js/SearchBox.vue
    27 │ import SearchBox from './SearchBox.vue';
       ╵                       ~~~~~~~~~~~~~~~~~

 > js/app.js:33:24: error: No loader is configured for ".vue" files: js/HelpMeanAge.vue
    33 │ import HelpMeanAge from './HelpMeanAge.vue';
       ╵                         ~~~~~~~~~~~~~~~~~~~

 > js/app.js:23:22: error: No loader is configured for ".vue" files: js/CorrTable.vue
    23 │ import CorrTable from './CorrTable.vue';
       ╵                       ~~~~~~~~~~~~~~~~~

 > js/app.js:32:27: error: No loader is configured for ".vue" files: js/HelpPrevalence.vue
    32 │ import HelpPrevalence from './HelpPrevalence.vue';
       ╵                            ~~~~~~~~~~~~~~~~~~~~~~

 > js/app.js:30:23: error: No loader is configured for ".vue" files: js/HelpButton.vue
    30 │ import HelpButton from './HelpButton.vue';
       ╵                        ~~~~~~~~~~~~~~~~~~

 > js/app.js:26:22: error: No loader is configured for ".vue" files: js/DrugTable.vue
    26 │ import DrugTable from './DrugTable.vue';
       ╵                       ~~~~~~~~~~~~~~~~~

 > js/app.js:25:23: error: No loader is configured for ".vue" files: js/AssocTable.vue
    25 │ import AssocTable from './AssocTable.vue';
       ╵                        ~~~~~~~~~~~~~~~~~~

0 of 4 warnings and 10 of 16 errors shown (disable the message limit with --log-limit=0)
** (Mix) `mix esbuild default --minify` exited with 1
```

**Comment by vincent-octo** [comment]
Now getting this error when browsing to any endpoint page. Strangely seems related to [a Phoenix v1.4 -> v1.5 upgrade](https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f#update-your-layouts) 
```
assign @view_module not available in template.

Please make sure all proper assigns have been set. If you are
calling a component, make sure you are passing all required
assigns as arguments.

Available assigns: [:broader_endpoints, :conn, :data_assocs, :description, :distrib_age, :distrib_year, :endpoint, :explainer_steps, :mortality, :narrower_endpoints, :ontology, :outpat_bump, :page_title, :stats]
```

**Comment by vincent-octo** [comment]
The code leading the `@view_module not available` error above comes from `show.html.heex`:
```elixir

			<%= render @view_module, "endpoint_explainer.html", steps: @explainer_steps, endpoint: @endpoint %>

```

This was the solution provided in the [Phoenix v1.4 docs to render sub-templates](https://hexdocs.pm/phoenix/1.4.0/views.html#a-word-about-layouts).
It still seemed to work with Phoenix v1.5, but not anymore with Phoenix v1.6 – though no mention of deprecation in the docs as far as I can tell.

**Comment by vincent-octo** [comment]
Replacing the erroring

```
<%= render @view_module, "endpoint_explainer.html", steps: @explainer_steps, endpoint: @endpoint %>
```

with 

```
<%= render(RisteysWeb.PhenocodeView, "endpoint_explainer.html", steps: @explainer_steps, endpoint: @endpoint) %>
```

worked.
